site_name: Programowanie w języku Python (I)
docs_dir: docs
repo_url: https://github.com/eo-agh/python1-materials
repo_name: python1-materials

copyright: Copyright 2024 Jakub Staszel KGiIS AGH

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Strona główna: index.md
  - Podstawy programowania:
    - 👽 Środowisko lokalne: zaj0/srod-lok.md
    - 👽 Git - kontrola wersji: zaj0/git.md
  - Podstawy Pythona:
    - 🌞 Moduły i przestrzenie nazw: zaj01/moduly_przestrzenie.md
    - 🌞 Podstawowe typy wbudowane: zaj01/typy_wbudowane.md
    - 🌞 Niespodziewane zachowania: zaj01/niespodziewane.md
    - 🌞 Instrukcje warunkowe i pętle: zaj01/instrukcje_petle.md
    - 🌞 Praca z plikami: zaj01/praca_z_plikami.md
    - 🌞📝 Zadanie sprawdzające: zaj01/zadania_sprawdzajace.md
    - 🌞 Przypisania: zaj01/przypisania.md
  - Pętle:
    - ❄️ Wstęp - pętle: zaj02/petle.md
    - ❄️ Listy składane: zaj02/listy_skladane.md
  - Funkcje:
    - ❄️ Wstęp - funkcje: zaj02/funkcje.md
    - ❄️ Funkcje anonimowe - lambda: zaj02/lambda.md
  - Programowanie obiektowe:
    - 🥕 Wstęp - klasy i instancje: zaj03/klasy.md
    - 🥕 Po co programować obiektowo?: zaj03/obiektowe_poco.md
    - 🥕 Dziedziczenie: zaj03/dziedziczenie.md
    - 🥕 Przeciążanie operatorów: zaj03/przeciazanie.md
    - 🥕 Narzędzia introspekcji: zaj03/introspekcja.md
    - 🥕 Atrybuty pseudoprywatne: zaj03/pseudoprywatne.md
    - 🥕📝 Zadania cz. 1: zaj03/zadania1.md
    - 🦄 Rodzaje metod: zaj04/metody.md
    - 🦄 Sloty: zaj04/sloty.md
    - 🦄 Abstrakcyjne klasy nadrzędne: zaj04/abstrakcyjne.md
    - 🦄 Rozszerzanie typów wbudowanych: zaj04/wbudowane.md
    - 🦄📝 Zadania cz. 2: zaj04/zadania2.md
  - Zaawansowane konstrukcje:
    - 🧩 Iteratory: zaj05/iteratory.md
    - 🧩 Generatory: zaj05/generatory.md
    - 🧩 Menadżery kontekstu: zaj05/menadzery_kontekstu.md
  - Pozostałe elementy języka:
    - 🤖 Obsługa wyjątków: zaj06/wyjatki.md
    - 🤖 Dekoratory: zaj06/dekoratory.md
  - Inżynieria oprogramowania:
    - 🛠️ Testy: zaj07/testy.md
    - 🛠️ Logowanie: zaj07/logowanie.md
    - 🧪 Środowiska wirtualne: zaj08/srodowiska_wirtualne.md
    - 🧪 Mamba i conda-lock: zaj08/mamba_condalock.md
